import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "@/redux/Provider";
import Footer from "@/components/Footer";
import { SearchPokemon } from "@/components/SearchPokemon";
import { SelectComponent } from "@/components/SelectComponent";
import SearchAndSelect from "@/components/SearchAndSelect";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Test Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <div className="container mx-auto children-wrapper">
          <Providers>
            <SearchAndSelect />
            <div>{children}</div>
          </Providers>
        </div>
        <Footer />
      </body>
    </html>
  );
}
